CPU-only op: SparseUnsortedSegmentWeightedSum
RuntimeError: [enforce fail at operator.cc:108] op. Cannot create
operator of type 'SparseUnsortedSegmentWeightedSum' on the device
'CUDA'. Verify that implementation for the corresponding device exist.
It might also happen if the binary is not linked with the operator
implementation code. If Python frontend is used it might happen if
dyndep.InitOpsLibrary call is missing. Operator def: input: "Y" input:
"val" input: "key" input: "seg" output: "out" name: "" type:
"SparseUnsortedSegmentWeightedSum" arg { name: "num_segments" i: 5 }
device_option { device_type: 1 }