CPU-only op: EnsureDense
RuntimeError: [enforce fail at operator.cc:108] op. Cannot create
operator of type 'EnsureDense' on the device 'CUDA'. Verify that
implementation for the corresponding device exist. It might also happen
if the binary is not linked with the operator implementation code. If
Python frontend is used it might happen if dyndep.InitOpsLibrary call is
missing. Operator def: input: "X" output: "X" name: "" type:
"EnsureDense" device_option { device_type: 1 }