Update centos.md
Add solution for trouble linking with "libCaffe2_GPU.so" due to "undefined reference to `ncclReduceScatter'".
Add "-DBUILD_SHARED_LIBS=ON" to glog building.